### ISSUE TITLE
Publish missing tags for later/latest releases

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/upickle#305]
Maven central lists 0.9.8 and 0.9.9, but the tags aren't there.

**Comment by lefou** [comment]
I saw, you pushed some tags. What about 0.9.9? https://search.maven.org/artifact/com.lihaoyi/upickle_2.13

**Comment by lihaoyi** [comment]
Probably can close this for now since we've been using tag-based publishing for a while
