### ISSUE TITLE
Non-side-effecting Read

### ISSUE THREAD

**Issue by peter-empen** [com-lihaoyi/upickle#312]
Hi Li,

what is your attitude towards an additional _read_ method that will never throw an exception? I mean a signature like
`def maybeRead[T: Reader](s: ujson.Readable): Either[String, T]`
where `String` would be the _message_ of the exception you are throwing.

Although this is easy to achieve on top of the current _read_, I still wonder whether it was worth to supply.

**Comment by lihaoyi** [comment]
Hi Peter!

This sounds alike a reasonable either (maybe called `readEither`?).

One issue with uPickle is I do not think it is sufficiently rigorous with what exceptions are thrown, when and why. Trying to stuff it into an `Either` or `Try` would be a good time to start adding tests for all the error cases, so we know exactly how uPickle behaves in each case

**Comment by peter-empen** [comment]
Yeah, `readEither` sounds really good, I'm not opinionated. In Circe `decode` returns the same.

Is that something you'd do soon or do you prefer me to give it a try?

**Comment by lihaoyi** [comment]
I won’t have time to take a crack at it any time soon, so go ahead

**Comment by peter-empen** [comment]
OK.
To finalize the signature, is it correct to assume that `read` always fails fast? Otherwise we better use a type that allows to return any number of failures.
And, if we just want to return a single failure, does it make sense to have a `ParseFailure` class instead of just using  `String`?

**Comment by lihaoyi** [comment]
yes currently read always fails fast with an exception

**Comment by peter-empen** [comment]
Concerning [PR 317](https://github.com/lihaoyi/upickle/pull/317), how can I compile against Scala 2.11 in _mill_ locally? I tried `upickle.jvm("2.11.12").compile()` but it does not work.

**Comment by peter-empen** [comment]
@lihaoyi Waiting for your kind review of https://github.com/lihaoyi/upickle/pull/317...

**Comment by lihaoyi** [comment]
Closing this as a wontfix together with https://github.com/com-lihaoyi/upickle/pull/317
