### ISSUE TITLE
Custom string interpolation

### ISSUE THREAD

**Issue by matthewsch-db** [com-lihaoyi/upickle#315]
I saw [this page in the Scala docs](https://docs.scala-lang.org/overviews/core/string-interpolation.html#advanced-usage) that explained Scala 2.10 allows for user defined string interpolation. For an example they gave a rudimentary `JsonHelper` string interpolator that converted something like `json"{ name: $name, id: $id }"` into the corresponding json object. I figured that could be a useful feature for `ujson`.

**Comment by lihaoyi** [comment]
going to call this a wontfix for now. The `ujson.*` literals should be good enough for most use cases
