### ISSUE TITLE
MessagePack: handle null values as None

### ISSUE THREAD

**Issue by vpodlnk** [com-lihaoyi/upickle#318]
Hi, I have a question about the library. Is there a possibility to treat `null` values as `None`?
I encode the data in C# using (https://github.com/neuecc/MessagePack-CSharp) which places `null` values for not initialized public members. Then I try to read the encoded data from Scala, but get this error
` java.util.NoSuchElementException: None.get`

**Comment by htmldoug** [comment]
https://com-lihaoyi.github.io/upickle/#CustomConfiguration describes how to map `null` to `None` in the section about Options.
