### ISSUE TITLE
Uninformative error when JSON missing $type attribute

### ISSUE THREAD

**Issue by JamesMcIntosh** [com-lihaoyi/upickle#320]
```
java.util.NoSuchElementException: None.get
    scala.None$.get(Option.scala:529)
    scala.None$.get(Option.scala:527)
    upickle.AttributeTagged$$anon$4.visitEnd(Api.scala:254)
```

This error happens when the JSON is expected to have an attribute `$type`

**Comment by lihaoyi** [comment]
Not sure when this was fixed, but I get a `expected tagged dictionary` error when `$type` is missing

**Comment by lihaoyi** [comment]
Added a test to enforce this in https://github.com/com-lihaoyi/upickle/pull/372, but it's been like that for a while AFAICT
