### ISSUE TITLE
"match may not be exhaustive" in macroRW for case class

### ISSUE THREAD

**Issue by raquo** [com-lihaoyi/upickle#345]
Hello, I was hoping to use [sbt-tpolecat](https://github.com/DavidGregory084/sbt-tpolecat) in a project of mine that depends on upickle, but it seems that macroRW is causing this compiler warning, so I can't make warnings fatal.

Minimized example: https://scastie.scala-lang.org/Pk7pFpgzT16Nccuyb7JKCA

```scala
import upickle.default._
case class Foo(num: Int)
val rw: ReadWriter[Foo] = macroRW
```

build.sbt
```
scalaVersion := "2.13.5"
scalacOptions ++= Seq("-Xlint",  "-Xfatal-warnings")
libraryDependencies += "com.lihaoyi" %% "upickle" % "1.3.8"
```

Result:

> match may not be exhaustive.
> It would fail on the following input: (x: Int forSome x not in 0)

**Comment by pthorin** [comment]
@raquo I also got this warning but I found that there is an option to suppress certain warnings since scala 2.13.2 (https://www.scala-lang.org/2021/01/12/configuring-and-suppressing-warnings.html), in my case I used annotations. This worked excellent for me with making warnings fatal.
