### ISSUE TITLE
Scala 3 serialization macros are very inefficient compared to Scala 2

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/upickle#389]
Compared Scala 2 (https://github.com/com-lihaoyi/upickle/tree/master/implicits/src-2/upickle/implicits) and Scala 3 (https://github.com/com-lihaoyi/upickle/tree/master/implicits/src-3/upickle/implicits) implementations. 

The Scala 2 implementation does not contain any runtime logic at all, and generates a single class at compile time for each case class in question. During reading, temporary values are stored unboxed in typed case class fields, accessed as fields, and put directly into class constructor. During writing, the case class fields are read and put directly into the visitor. That is all that happens at runtime.

The Scala 3 implementation does a bunch of runtime reflection to get fields, puts values boxed in temporary lists and `Map[String, Any]`s, does dictionary lookups, and all sorts of other things like that. While it passes tests, it is likely an order of magnitude slower than the Scala 2 implementation, and really should be re-written to be in the same style: do all reflection at compile-time, generating lean and efficient code to do minimal work at runtime

**Comment by jodersky** [comment]
I am happy to take a look at it. It would be a good opportunity to also check #386.

**Comment by lihaoyi** [comment]
Thanks @jodersky! I was planning on releasing 2.0.0 since the other PRs have merged, but if you're going to take a look at this I can hold off a week to see if we can include your work. The proposed changes will affect binary compatibility for Scala 3 if I'm not mistake

**Comment by jodersky** [comment]
> the proposed changes will affect binary compatibility for Scala 3 if I'm not mistake

are you talking about binary compatibility of 2.0 or macros? In case you mean the latter, I don't think that anything would change. The macros are a black box, right? They will generate instances of the ReadWriters, but beyond that they are totally opaque to user programs. What I'm saying is that while I appreciate you willing to hold off on 2.0 for a little, I don't think you have to :)  We could release fixes to macros in a 2.1 or other patch release.

**Comment by lihaoyi** [comment]
@jodersky I'm imagining a case where someone compiles against scala3/upickle2 with the current macros+runtimesupport, we release a new scala3/upickle2+ without the runtime support, and then someone using their their earlier-compiled macro serializers against the newer version of upickle hits NoSuchMethod errors. The earlier-compiled code would still have callsites to the runtime support code which gets removed in upickle 2+

On the other hand, I would guess that anyone dealing with Scala3 would be OK with some amount of instability, so I'll probably release upickle 2 as is and the scala 3 users can deal with the upickle 2+ breakage by upgrading when the time comes

**Comment by smarter** [comment]
You could also keep the runtime support without using it, just to support old versions.

**Comment by htmldoug** [comment]
@russellremple was able to reduce quite a bit of the penalty when he ported the upickle 3 macros to weepickle in https://github.com/rallyhealth/weePickle/pull/81, mostly by removing those runtime Maps. Even so, they're still slower than the scala 2 macros.

[These](https://github.com/rallyhealth/weePickle/blob/v1/bench/src/main/scala/bench/ScalaVersionBench.scala) benchmark [results](https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/htmldoug/88ce49b0eb400df62bc5235ea5140b70/raw/839fd45bce6794f7e7207db56051b83c4aa2343d/bench-310.json,https://gist.githubusercontent.com/htmldoug/88ce49b0eb400df62bc5235ea5140b70/raw/839fd45bce6794f7e7207db56051b83c4aa2343d/bench-213.json) show the change in the case class macros, i.e. no JSON parsing, between scala 3.1.0 and 2.13.8 for both weepickle and upickle 2.0.0.

**Comment by russellremple** [comment]
Yep, we added a lot of caching and other fine tunings to avoid many of the unnecessary Map builds, etc. But underlying macros are still slower. Note there were other Scala 3 enhancements in https://github.com/rallyhealth/weePickle/pull/94 to support auto-derivation for Scala 3 enums, but that didn't really affect performance. (But it is really cool IMO.)
