### ISSUE TITLE
Conflicting Circe versions in build.sc

### ISSUE THREAD

**Issue by dvgica** [com-lihaoyi/upickle#450]
I'm not terribly familiar with Mill, but it looks like there are conflicting versions of Circe present in `build.sc`:
- 0.13.0 [here](https://github.com/com-lihaoyi/upickle/blob/main/build.sc#L357)
- 0.14.4 [here](https://github.com/com-lihaoyi/upickle/blob/main/build.sc#L442)

This scala-steward PR updated the second, but not the first (although it was already de-synced): https://github.com/com-lihaoyi/upickle/pull/442/files

In my project dependencies, 0.13.0 is being pulled in a result, and it's pretty old. Any reason the version can't be updated everywhere?

**Comment by lihaoyi** [comment]
Seems to be gone now that everyone is on 0.14.5
