### ISSUE TITLE
Manual use of macroRW on enum creates infinite loop

### ISSUE THREAD

**Issue by rgwilton** [com-lihaoyi/upickle#468]
When moving to version 3.0.0, I get the following warning for

Starting compilation server
```
[warn] ./scripts/helper.sc:277:40
[warn] Infinite loop in function body
```

for this code:

```
given rwConfigType: ReadWriter[ConfigType] = macroRW, where ConfigType is defined as:

enum ConfigType:
  case Config, ConfigStructural, StateAppliedConfig, StateDerived, StateStructural, Unknown
```

 , which I can confirm at run time that the compile warning is indeed correct ;-).

Deleting the given and adding a "derives ReadWriter" fixes the issue, but thought that it would be helpful to flag this.

**Comment by ioleo** [comment]
Just had the same issue. Thanks for the workaround.

**Comment by lihaoyi** [comment]
There's a problem with the user code, you should be using `macroRWAll` if you want to derive a readwriter for the parent `enum` type without manually deriving `macroRW`s for all the enum cases.

The error message is misleading, and can probably be improved
