### ISSUE TITLE
Implicit conversion can easily lead to lost data

### ISSUE THREAD

**Issue by szeiger** [com-lihaoyi/upickle#512]
After refactoring some code from putting data into an `ujson.Obj` to directly updating the underlying `LinkedHashMap` we were left with code like this:
```
    val j = mutable.LinkedHashMap[String, ujson.Value]()
    j.value.put("n", ujson.Str(name))
    ujson.Obj(j)
```
It compiles without warnings but the `n` field never makes it into the object. The unnecessary `.value` call which got the underlying map from the previously used Obj now triggers an implicit conversion that copies the map:
```
  implicit def JsonableDict[T](items: TraversableOnce[(String, T)])
                              (implicit f: T => Value): Obj = Obj.from(items.map(x => (x._1, f(x._2))))
```
The new entry is only written into the copy and immediately discarded.

I'm not sure what the right solution is. Clearly `.value` is necessary. The implicit conversion could be removed but it may make the API harder to use in some cases.

**Comment by lihaoyi** [comment]
Probably going to call this a wontfix. Copying mutable data structures around always has this risk, or the opposite risk of unexpected aliasing and side effects. Given `ujson.Value` is designed to be mutable, there's really no way around it
