### ISSUE TITLE
Reading json with more than 16 digits is converted to scientific notation

### ISSUE THREAD

**Issue by mokexinxin** [com-lihaoyi/upickle#520]
When I use it, the parameters passed in are：
`{'a':11111111111111111111111111111111}`

The result I got is：
`{"a":1.1111111111111112E31}`

I want to get the number itself, not the scientific notation. Is there a solution?

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/com-lihaoyi/upickle/pull/521, which allows you to parse the number as a `String` if you want to preserve the full literal contents

```
          upickle.default.read[Map[String, String]]("""{"a":11111111111111111111111111111111}""") ==
          Map("a" -> "11111111111111111111111111111111")
```
