### ISSUE TITLE
Case class deserialization doesn't go through `apply` in Scala 3

### ISSUE THREAD

**Issue by smarter** [com-lihaoyi/upickle#552]
https://com-lihaoyi.github.io/upickle/#Basics says:
> Case classes are serialized using the apply and unapply methods on their companion objects. 

This isn't the case in Scala 3:
```scala
case class Foo(x: Int) derives ReadWriter
object Foo:
  def apply(x: Int): Foo =
    assert(x > 0)
    new Foo(x)
@main def Test =
  read[Foo]("""{"x":-1}""") // Successfully constructs a Foo.
```

This is because deserialization uses `Mirror#fromProduct` which just calls the constructor: https://github.com/com-lihaoyi/upickle/blob/6e551ac735781b2921913108d5377ceccd7bbed5/upickle/implicits/src-3/upickle/implicits/Readers.scala#L72

**Comment by lihaoyi** [comment]
@smarter would you be able to help review the PR fixing this issue? I'm not familiar with Scala 3 metaprogramming https://github.com/com-lihaoyi/upickle/pull/607/files
