### ISSUE TITLE
Missing uPickle 3.1.5 artifact for Scala 3

### ISSUE THREAD

**Issue by martin-ockajak** [com-lihaoyi/upickle#558]
It seems something might have gone wrong during the publishing process because uPickle 3.1.5 artifact is missing among [published versions](https://central.sonatype.com/artifact/com.lihaoyi/upickle_3/versions).

However, the artifact for Scala 2.13 is [there](https://central.sonatype.com/artifact/com.lihaoyi/upickle_2.13/versions).

The missing artifact would also explain this [commented out check](https://github.com/com-lihaoyi/upickle/blob/153efbd23aaff5707feb52e162d89e7acc2ff352/build.sc#L55C1-L55C90).

**Comment by lihaoyi** [comment]
Can you try using 3.2.0? 3.1.5 had some issues so i published a follow up release

**Comment by martin-ockajak** [comment]
Sure, thanks for making that available 😄.
