### ISSUE TITLE
Allow `$type` tag to be replaced by some other string (500USD Bounty)

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/upickle#578]
Given a `"$type": "foo.Bar"` sealed trait discriminator, [Custom Keys](https://com-lihaoyi.github.io/upickle/#CustomKeys)'s `@key` annotation allows you to replace the right hand side `"foo.Bar"` of a particular `case class` by annotating the `case class`, but it does not allow you to replace to left hand side `"$type"` string with something else. 

This ticket is to implement the ability for a user to replace `$type"` with some other string, by annotating the `sealed trait` itself with `@key("myType")` annotation that would replace `"$type"` with `"myType"` for all sub-classes of the `sealed trait`.

To incentivize contribution, I'm putting a 500USD bounty on resolving this ticket. This is payable via bank transfer, and at my discretion in case of ambiguity.

**Comment by mrdziuban** [comment]
I'd be happy to take a stab at this @lihaoyi 

Is it okay if the `LegacyApi` continues to use `$type` for the discriminator and only `upickle.default` uses the new behavior?

**Comment by lihaoyi** [comment]
IIRC the legacy one doesnt use a key value discriminator at all; instead, it wraps things jn two element arrays

**Comment by lihaoyi** [comment]
But yeah, I think in general focusing on making it work for upickle.default is fine.
