### ISSUE TITLE
Chrome on ARM freezes

### ISSUE THREAD

**Issue by matthewdunbar** [com-lihaoyi/upickle#589]
When running Chrome v126 on ARM devices, calling `upickle.default.write(...)` multiple times eventually causes Chrome to freeze. We verified this is affecting both Android phones and M1 based Macs (and likely other ARM based devices)

I have created a minimal reproducible example here with instructions to replicate the bug: https://github.com/matthewdunbar/scalajs-chrome-bug-example

We suspect this is a bug in Chrome since our code runs correctly on v125 but starts having issues on v126. Does anyone have any thoughts on how to resolve this?

**Comment by rmmeans** [comment]
We also noted that it this works _successfully_ on:
* Chrome 126 on intel (e.g. windows)
* Firefox on ARM
* Safari on ARM.

Whatever happened in Chrome 126 on ARM has caused some sort of issue. Something with the Javascript instruction set that uPickle creates and then when that instruction gets JIT'd on ARM it causes a bug that spikes the process in chrome to 100% and deadlocks that chrome process. 

As Matthew noted, this is hits on serializing *anything*, so I'd expect this to come up pretty quickly for uPickle users as Chrome 126 adoption rate goes up.

**Comment by rmmeans** [comment]
This simple app pegs the chrome process on this tab out at 99% and deadlocks (never completes). Only happens on Chrome 126 on ARM.

<img width="1186" alt="image" src="https://github.com/com-lihaoyi/upickle/assets/3507512/be02a995-6145-4520-b08e-8497c0be8a01">

**Comment by ekrich** [comment]
Can't you submit the Javascript/repo to the Chrome (assuming you are not running through GCC)?

**Comment by rmmeans** [comment]
We are already in process! Hopefully others who hit this won't open a ticket on uPickle for this. It's a big impact though - serializing even a simple string with uPickle on chrome 126 causes the break.

**Comment by matthewdunbar** [comment]
We've figured out a workaround to prevent this issue. For now we forked upickle, but here's a PR if you're interested in it:
https://github.com/com-lihaoyi/upickle/pull/590

**Comment by lihaoyi** [comment]
Hopefully should get worked around by https://github.com/com-lihaoyi/upickle/pull/590
